# -*- coding: utf-8 -*-
"""AL_CNN-1D_MC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/138kXfeUEyWl26PA9bRTGxJQk-9vF3iyS
    
    
        ACTIVE LEARNING MULTI-COUCHES

"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from keras.models import Sequential
from keras.layers import BatchNormalization

from google.colab import drive
drive.mount('/content/drive')
path = 'drive/My Drive/dataset'
data = pd.read_csv(path + "/IoT Network Intrusion Dataset.csv",low_memory=False)

col_in = []
for i in data.columns:
    unique_values = data[i].nunique()
    if unique_values == 1:
        col_in.append(i)
    else:
            continue

# Supprimer les colonnes inutiles
col_in = ['Fwd_Pkt_Len_Std', 'Bwd_Pkt_Len_Std', 'Flow_IAT_Std', 'Fwd_IAT_Tot', 'Fwd_IAT_Mean', 'Fwd_IAT_Std', 'Fwd_IAT_Max', 'Fwd_IAT_Min', 'Bwd_IAT_Tot', 'Bwd_IAT_Mean', 'Bwd_IAT_Std', 'Bwd_IAT_Max', 'Bwd_IAT_Min', 'Fwd_PSH_Flags', 'Bwd_PSH_Flags', 'Fwd_URG_Flags', 'Bwd_URG_Flags', 'Pkt_Len_Std', 'Pkt_Len_Var', 'FIN_Flag_Cnt', 'SYN_Flag_Cnt', 'RST_Flag_Cnt', 'PSH_Flag_Cnt', 'URG_Flag_Cnt', 'CWE_Flag_Count', 'ECE_Flag_Cnt', 'Down/Up_Ratio', 'Fwd_Byts/b_Avg', 'Fwd_Pkts/b_Avg', 'Fwd_Blk_Rate_Avg', 'Bwd_Byts/b_Avg', 'Bwd_Pkts/b_Avg', 'Bwd_Blk_Rate_Avg', 'Fwd_Seg_Size_Min', 'Active_Mean', 'Active_Std', 'Active_Max', 'Active_Min', 'Idle_Std']
data.drop(columns=col_in, inplace=True)

# Supprimer les colonnes non numériques
data.drop(columns=['Timestamp', 'Fwd_Pkt_Len_Mean', 'Bwd_Pkt_Len_Mean', 'Flow_IAT_Mean', 'Pkt_Len_Mean', 'Idle_Mean'], inplace=True)

#Remplacer les valeurs manquantes par 0

data.fillna(0)

#Supprimer les informations dupliquées
data = data.drop_duplicates(keep='first')

# Séparer les caractéristiques et les étiquettes
X = data.drop(columns=['Label', 'Cat', 'Sub_Cat'])
y = data['Cat']

from sklearn.preprocessing import OrdinalEncoder

# Encoder les colonnes catégoriques
encoder = OrdinalEncoder()
cat_cols = ['Flow_ID','Src_IP','Dst_IP']
X[cat_cols] = encoder.fit_transform(X[cat_cols])

# Identifier les valeurs infinies
contains_infinity = np.any(np.isinf(X))

if contains_infinity:
    # Remplacer les valeurs infinies par des NaN (pour les exclure de la normalisation)
    X[np.isinf(X)] = np.nan

    # Remplacer les NaN par une valeur appropriée (par exemple, 0)
    X = np.nan_to_num(X, nan=0.0)

#Encoder les classes avec OneHotEncoder
OHEncoder = OneHotEncoder()
y = OHEncoder.fit_transform(y.values.reshape(-1,1)).toarray()

# Normalisation des caractéristiques
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

#Convertir les champs en "float64"
X = X.astype(np.float64)

#Convertir les étiquettes en "float64"
y = y.astype(np.float64)

y# Diviser les données en ensembles de formation et de test
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

y_test

from keras.layers import BatchNormalization
def model():
    model = Sequential()
    model.add(Conv1D(75, kernel_size=3, strides=1, padding="same", activation="relu",  input_shape=(x_train.shape[1],1)))
    model.add(BatchNormalization())
    model.add(MaxPooling1D(2, strides = 2, padding="same"))
    model.add(Conv1D(50, kernel_size=3, strides=1, padding="same", activation="relu"))
    model.add(Dropout(0.2))
    model.add(BatchNormalization())
    model.add(MaxPooling1D(2, strides=2, padding="same"))
    model.add(Conv1D(25, kernel_size=3, strides=1, padding="same", activation="relu"))
    model.add(BatchNormalization())
    model.add(MaxPooling1D(2, strides=2, padding="same"))
    model.add(Flatten())
    model.add(Dense(units=512, activation="relu"))
    model.add(Dropout(0.3))
    model.add(Dense(units=5, activation="softmax"))

    model.compile(optimizer='adam',loss="categorical_crossentropy", metrics=["accuracy"])
    return model

!pip install scikeras
from scikeras.wrappers import KerasClassifier

# create the classifier
classifier = KerasClassifier(model)

# Choisir les données d'entraînement initiales de l'apprentissage actif de manière aléatoire
n_initial = 50000
initial_idx = np.random.choice(range(len(x_train)), size=n_initial, replace=False)
x_initial = x_train[initial_idx]
y_initial = y_train[initial_idx]

# Supprimer les données initiales du reste des données d'apprentissage
x_pool, y_pool = np.delete(x_train, initial_idx, axis=0), np.delete(y_train, initial_idx, axis=0)
#x_pool_test, y_pool_test = np.delete(x_test, initial_idx, axis=0), np.delete(y_test, initial_idx, axis=0)

!pip install git+https://github.com/modAL-python/modAL.git

from modAL.uncertainty import uncertainty_sampling
from modAL.models import ActiveLearner

# Initialisation de ActiveLearner
learner = ActiveLearner(
    estimator=classifier,
    query_strategy=uncertainty_sampling,
    X_training=x_initial,
    y_training=y_initial,
    verbose=1
)

from IPython import display
from matplotlib import pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import numpy as np

# Boucle d'Active Learning
n_queries = 15  # Nombre d'exemples à étiqueter
accuracy_scores = [learner.score(x_test, y_test)]
accuracy_scores=[]
pr=[]
recal=[]
f1_s =[]
losses =[]
cm = []

for idx in range(n_queries):
    print('Query no. %d' % (idx+1))
    #query_idx, query_instance = learner.query(X_pool.reshape(-1, X_pool.shape[1], 1),n_instances=100, verbose=0)
    query_idx, query_instance = learner.query(x_pool,n_instances=100,verbose=0)
    learner.teach(x_pool[query_idx], y_pool[query_idx],only_new=True)
    y_pred = learner.predict(x_test)
    y_pred = np.round(y_pred)
    accurracy = learner.score(x_test,y_test)
    precision = precision_score(y_test, y_pred,average='macro')
    recall = recall_score(y_test, y_pred,average='macro')
    f1 = f1_score(y_test, y_pred,average='macro')
    # Calculer la matrice de confusion
    confusion = confusion_matrix(np.argmax(y_test, axis=1), np.argmax(y_pred, axis=1))
    accuracy_scores.append(accurracy)
    pr.append(precision)
    recal.append(recall)
    f1_s.append(f1)



    cm.append(confusion)

    print('Accuracy after query %d: %f' % (idx + 1, accurracy))

loss_list = []

accuracy_scores

import matplotlib as mpl
import matplotlib.pyplot as plt
# Définir le point de départ pour l'axe y
start_y = 0.901# Remplacez cette valeur par celle que vous souhaitez

fig, ax = plt.subplots(figsize=(8.5, 6), dpi=130)

ax.plot(accuracy_scores)
ax.scatter(range(10), accuracy_scores, s=13)

ax.xaxis.set_major_locator(mpl.ticker.MaxNLocator(nbins=5))
ax.yaxis.set_major_locator(mpl.ticker.MaxNLocator(nbins=20))
ax.yaxis.set_major_formatter(mpl.ticker.PercentFormatter(xmax=1))

# Définir la limite inférieure de l'axe y
ax.set_ylim(bottom=start_y, top=1)

ax.grid(True)


ax.set_xlabel('Numbre epoch')
ax.set_ylabel('Accuracy')

plt.show()

import matplotlib as mpl
import matplotlib.pyplot as plt
# Définir le point de départ pour l'axe y
start_y = 0.0001# Remplacez cette valeur par celle que vous souhaitez

fig, ax = plt.subplots(figsize=(8.5, 6), dpi=130)

ax.plot(loss_list)

ax.grid(True)


ax.set_xlabel('Numbre epoch ')
ax.set_ylabel('Loss')
plt.show()





